---
version: "2.1"
services:
  medusa:
    image: ghcr.io/linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Colombo
    volumes:
      - /home/thilanka/apps/medusa/config:/config
      - /home/thilanka/Videos:/downloads
      - /home/thilanka/Videos/Tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
